name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'
  push:
    branches:
      - chore/renovate_action
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.141.0
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.GH_CQ_BOT }}